import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ProductCatalog from "@/pages/products/product_catalog";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Product Catalog </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p> Product Catalog </p>
          <div>
            <a
              href="https://coopbankoromia.com.et/"
              target="_blank"
              rel="noopener noreferrer"
            >
             
              <Image
                src="/coop.png"
                alt="Vercel Logo"
                width={100}
                height={100}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <ProductCatalog />
        </div>
        <div>
          <Footer/>
        </div>

        <div></div>
      </main>
    </>
  );
}
